name: Prettier Format (pokedex-engine)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pokedex-engine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Prettier Check Format
        run: bun run check-format
